In [1]:
import numpy as np

### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
# code here

arr = np.array([[92, 90, 74],
      [ 6, 63, 93],
      [15, 93, 96],
      [70, 60, 48]])

# i.sortin'

print(np.sort(arr))

[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]


In [3]:
# ii. based on 2nd column 

select_col = arr[:,1]
sorted_arr = arr[select_col.argsort()]

print(sorted_arr)

[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]


In [4]:
# iii. based on row max-ascending 

row_max = arr.max(axis=1)

sorted_arr = arr[row_max.argsort()[::-1]]
print(sorted_arr)

[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]


In [5]:
# iv. based on elements value 

sorted_elements = np.sort(arr, axis=None).reshape(arr.shape)

print(sorted_elements)

[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


### `Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
# Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [6]:
# code here

marks = np.array([
    [13, 10,  9, 33],
    [63, 46, 90, 42],
    [39, 76, 13, 29],
    [82,  9, 29, 78],
    [67, 61, 59, 36]
])

extra_subject = np.array([41, 87, 72, 36, 92])
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

# i) Add extra subject (as a new column)
marks = np.hstack((marks, extra_subject.reshape(-1, 1)))

# ii) Add two new students (as new rows)
marks = np.vstack((marks, rec1, rec2))

# iii) Add total marks column (sum of 5 subjects)
totals = marks.sum(axis=1).reshape(-1, 1)
marks = np.hstack((marks, totals))

# iv) Sort by total marks descending and show top 2 rows
sorted_marks = marks[marks[:, -1].argsort()[::-1]]
top2 = sorted_marks[:2]

print("Final array with totals:\n", marks)
print("\nTop 2 students by total marks:\n", top2)

Final array with totals:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Top 2 students by total marks:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


### `Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [7]:
# code here

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

# Row-wise unique
row_unique = np.unique(arr, axis=0)

# Column-wise unique
col_unique = np.unique(arr.T, axis=0).T

print("Row Wise")
print(row_unique)

print("\nCol Wise")
print(col_unique)

Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


### `Q-4:` Flip given 2-D array along both axes at the same time.

In [8]:
# code here

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

flipped = arr[::-1, ::-1]
print(flipped)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [9]:
# code here

arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

X = 6

rows = np.where(np.any(arr > X, axis=1))[0]

print("Row indices:", rows)

Row indices: [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [10]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [11]:
# code here

flat = np.concatenate((arr1, arr2, arr3))
print(flat)

[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [12]:
# code here

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

# find min and max
min_val = arr.min()
max_val = arr.max()

# flatten array
arr_flat = arr.flatten()

# remove min and max
new_arr = arr_flat[(arr_flat != min_val) & (arr_flat != max_val)]

print("Minimum:", min_val)
print("Maximum:", max_val)
print("Array after removing min & max:")
print(new_arr)

Minimum: 103
Maximum: 998
Array after removing min & max:
[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [13]:
# code here

np.random.seed(400)
arr = np.random.randint(100, 700, 20)

print("Original array:")
print(arr)

# limit values between 100 and 200
arr_limited = np.clip(arr, 100, 200)

# sort array
sorted_arr = np.sort(arr_limited)

# cumulative sum
cumsum_arr = np.cumsum(sorted_arr)

print("\nLimited array:")
print(arr_limited)

print("\nSorted array:")
print(sorted_arr)

print("\nCumulative sum:")
print(cumsum_arr)

Original array:
[448 563 418 240 507 362 345 236 291 298 639 458 387 262 613 267 181 425
 635 277]

Limited array:
[200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 181 200
 200 200]

Sorted array:
[181 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative sum:
[ 181  381  581  781  981 1181 1381 1581 1781 1981 2181 2381 2581 2781
 2981 3181 3381 3581 3781 3981]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [14]:
# code here

np.random.seed(400)
arr = np.random.random(20)

# round to 3 decimal places
arr = np.round(arr, 3)

# percentiles
p0 = np.percentile(arr, 0)
p100 = np.percentile(arr, 100)

p50 = np.percentile(arr, 50)
p51 = np.percentile(arr, 51)

difference = p51 - p50

print("Array:", arr)
print("\n0th Percentile:", p0)
print("Minimum:", arr.min())

print("\n100th Percentile:", p100)
print("Maximum:", arr.max())

print("\nDifference between 51st and 50th percentile:", difference)

Array: [0.669 0.226 0.859 0.29  0.148 0.012 0.776 0.405 0.856 0.539 0.51  0.376
 0.172 0.153 0.924 0.035 0.847 0.638 0.499 0.97 ]

0th Percentile: 0.012
Minimum: 0.012

100th Percentile: 0.97
Maximum: 0.97

Difference between 51st and 50th percentile: 0.0020900000000000363
