**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here 

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###  `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here

import random
a, b = map(int, input("Enter two numbers (separated by a space): ").split())

rand = np.random.rand(a,b)
print(rand)
print(np.mean(rand))

Enter two numbers (separated by a space):  4 5


[[0.60939624 0.03391488 0.21982705 0.28956895 0.09218116]
 [0.52534135 0.22903423 0.06091166 0.1776663  0.19691422]
 [0.84272334 0.78366134 0.53764337 0.27487078 0.39949917]
 [0.71648262 0.23430898 0.37930631 0.15928557 0.54931915]]
0.3655928334183515


###  `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
#Code here

def create_2d_array(a, b):
    arr = np.zeros((a, b), dtype=int)
    
    arr[0] = 1          # top row
    arr[-1] = 1         # bottom row
    arr[:, 0] = 1       # left column
    arr[:, -1] = 1      # right column
    
    return arr


a, b = map(int, input("Enter two numbers (separated by space): ").split())
print(create_2d_array(a, b))


Enter two numbers (separated by space):  5 5


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [5]:
#Code here

vector = np.linspace(0, 1, num=12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [6]:
#Code here
# :((( identity matrix of 3,4
arr = np.zeros((3,4), int)
np.fill_diagonal(arr, 1)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [7]:
arr = np.zeros((5,5), int)
np.fill_diagonal(arr, 1)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [8]:
#Code here

x = np.arange(5).reshape(1,5).repeat(5, axis=0)

print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [9]:
#code here

points = np.random.randint(1, 101, size=(10,2))

given_point = np.array([2, 3])
distances = (np.sqrt(np.sum((points - given_point) ** 2, axis=1))).astype(int)

print("Points: \n", points)
print("Distances: \n", distances)

Points: 
 [[44 45]
 [72 62]
 [38 93]
 [59 36]
 [52 12]
 [20 33]
 [29 88]
 [40 55]
 [15 69]
 [29  5]]
Distances: 
 [59 91 96 65 50 34 89 64 67 27]


### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [10]:
#Code here

shape = (6, 7, 8)
idx = np.unravel_index(99, shape)

print(idx)

(np.int64(1), np.int64(5), np.int64(3))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [11]:
#Code here

inp = np.array([1, 2, 3, 4, -8, -10])
print((inp[::-1]).astype(float))

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count
Count the number of elements of a numpy array.

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [12]:
#Code here

arr = np.array([1, 2])
print(arr.size)

2


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [13]:
#Code here

data = list(map(float, input("Enter numbers separated by space: ").split()))
arr = np.array(data)

shifted = arr - np.max(arr)
exp_vals = np.exp(shifted)
softmax = exp_vals / np.sum(exp_vals)

print(softmax)

Enter numbers separated by space:  5 5


[0.5 0.5]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [14]:
#Coder here

a= np.array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]])

b= np.array([[1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

c= np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
 [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

res = np.vstack([a, b, c])
print(res)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [15]:
#Code here

start_date_str = input("Enter start date in YYYY-MM-DD format: ")
end_date_str = input("Enter end date in YYYY-MM-DD format: ")
start_date = np.datetime64(start_date_str)
end_date = np.datetime64(end_date_str)

dates = np.arange(start_date, end_date+np.timedelta64(1, 'D'), dtype='datetime64[D]')
print(dates)

Enter start date in YYYY-MM-DD format:  2025-12-31
Enter end date in YYYY-MM-DD format:  2026-09-10


['2025-12-31' '2026-01-01' '2026-01-02' '2026-01-03' '2026-01-04'
 '2026-01-05' '2026-01-06' '2026-01-07' '2026-01-08' '2026-01-09'
 '2026-01-10' '2026-01-11' '2026-01-12' '2026-01-13' '2026-01-14'
 '2026-01-15' '2026-01-16' '2026-01-17' '2026-01-18' '2026-01-19'
 '2026-01-20' '2026-01-21' '2026-01-22' '2026-01-23' '2026-01-24'
 '2026-01-25' '2026-01-26' '2026-01-27' '2026-01-28' '2026-01-29'
 '2026-01-30' '2026-01-31' '2026-02-01' '2026-02-02' '2026-02-03'
 '2026-02-04' '2026-02-05' '2026-02-06' '2026-02-07' '2026-02-08'
 '2026-02-09' '2026-02-10' '2026-02-11' '2026-02-12' '2026-02-13'
 '2026-02-14' '2026-02-15' '2026-02-16' '2026-02-17' '2026-02-18'
 '2026-02-19' '2026-02-20' '2026-02-21' '2026-02-22' '2026-02-23'
 '2026-02-24' '2026-02-25' '2026-02-26' '2026-02-27' '2026-02-28'
 '2026-03-01' '2026-03-02' '2026-03-03' '2026-03-04' '2026-03-05'
 '2026-03-06' '2026-03-07' '2026-03-08' '2026-03-09' '2026-03-10'
 '2026-03-11' '2026-03-12' '2026-03-13' '2026-03-14' '2026-03-15'
 '2026-03-

### `Q-14:` Subtract the mean of each row from a matrix.

In [16]:
#code here
arr = np.linspace(1,100, num=25, dtype=int)
matrix = arr.reshape(5,5)

# row_means = [np.mean(matrix[i]) for i in range(len(matrix))] # sad: bad way
# final_matrix = [(matrix[i] - row_means[i]) for i in range(len(matrix))] # sad: bad way

# we expect numpy to behave this way
row_means = matrix.mean(axis=1, keepdims=True)
final_matrix = matrix - row_means

print(matrix)
print(final_matrix)

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[[-8.  -4.   0.   4.   8. ]
 [-8.4 -4.4 -0.4  4.6  8.6]
 [-8.  -4.   0.   4.   8. ]
 [-8.8 -3.8  0.2  4.2  8.2]
 [-8.2 -4.2 -0.2  3.8  8.8]]


### `Q-15:` Swap column-1 of array with column-2 in the array.

In [17]:
#Code here

arr = np.linspace(1,100, num=25, dtype=int)
matrix = arr.reshape(5,5)
temp = matrix.copy()
print(matrix)

matrix[ :, 0] = temp[ :, 2]
matrix[:, 2] = temp[:, 0]
print(matrix)

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[[  9   5   1  13  17]
 [ 29  25  21  34  38]
 [ 50  46  42  54  58]
 [ 71  67  62  75  79]
 [ 91  87  83  95 100]]


### `Q-16:` Replace odd elements in arrays with -1.

In [18]:
#Code here

arr = np.linspace(1,100, num=25, dtype=int)
matrix = arr.reshape(5,5)

matrix[matrix % 2 == 1] = -1
print(matrix)

[[ -1  -1  -1  -1  -1]
 [ -1  -1  -1  34  38]
 [ 42  46  50  54  58]
 [ 62  -1  -1  -1  -1]
 [ -1  -1  -1  -1 100]]


### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [19]:
#Code here

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

result = np.maximum(a, b)
print(result)

[6 3 1 7 8]


### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [21]:
# Given
arr = np.random.randint(low=1, high=10000, size=40).reshape(8,5)
mean = arr.mean(axis=0)
std = arr.std(axis=0)

print("Alternate Cols :\n", arr[:, ::2])
print("Normalized : \n", (arr - mean) / std)

Alternate Cols :
 [[ 211 3109 5661]
 [9980 7115 8140]
 [4185 2024 7415]
 [7044 4386 9366]
 [6521 1058 4696]
 [7457 8386 8097]
 [9418 7750 5623]
 [6542  677 4766]]
Normalized : 
 [[-2.15026336 -0.8217382  -0.41681857  0.74412437 -0.64424781]
 [ 1.23301391 -1.49590925  0.96989392 -1.4627556   0.86315221]
 [-0.77395628 -0.17033465 -0.79240095  0.85643203  0.42230307]
 [ 0.21619519 -0.62020364  0.02522633  1.40970229  1.60864331]
 [ 0.0350657   1.28720714 -1.12679044 -0.76961752 -1.23103322]
 [ 0.35922862  0.53292821  1.40986186  0.42718251  0.8370053 ]
 [ 1.03837763 -0.33139365  1.18970481  0.13401129 -0.66735439]
 [ 0.04233859  1.61944403 -1.25867697 -1.33907937 -1.18846847]]


### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [22]:
#Code here
import numpy as np

def nth_largest(arr, n):
    if n > len(arr):
        raise ValueError("n must be <= length of array")
    
    return np.partition(arr, -n)[-n]

arr = np.array([12, 34, 40, 7, 1, 0])

print(nth_largest(arr, 3))  # 12
print(nth_largest(arr, 1))  # 40

12
40


### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [23]:
#code here

a = np.array([1,2,3])

part1 = np.repeat(a, len(a))
print(part1)
part2 = np.tile(a, len(a))
print(part2)
result = np.concatenate((part1, part2))

print(result)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
